# Generated by Django 5.0.4 on 2024-04-18 19:36

import account.managers
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('modify_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('username', models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator(message='Only alphanumeric characters and underscores are allowed.', regex='^[a-zA-Z0-9_]*$')])),
                ('password', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Password must contain at least 8 characters, including uppercase, lowercase, and digits.', regex='^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)[a-zA-Z\\d]{8,}$')])),
                ('phone_number', models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid Iranian phone number.', regex='^(?:\\+989|09|00989)(?:0[0-5]|1[0-9]|2[0-3]|3[02-9]|9[0-46])[0-9]{7}$')])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('is_logged_in', models.BooleanField(default=False)),
                ('profile_image', models.ImageField(blank=True, default='profile_images/User_Default_Profile_Pic.png', upload_to='profile_images/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'indexes': [models.Index(fields=['username'], name='account_cus_usernam_9f698e_idx'), models.Index(fields=['email'], name='account_cus_email_5f481e_idx'), models.Index(fields=['phone_number'], name='account_cus_phone_n_bc0a85_idx')],
            },
            managers=[
                ('objects', account.managers.UserManager()),
            ],
        ),
    ]
