# Generated by Django 5.0.4 on 2024-04-21 20:16

from django.db import migrations
from account.models import CustomUser


def populate_users(apps, schema_editor): # noqa: unused-argument
    CustomUser.objects.create(
        username='Fardin_Zand',
        password='12345678',
        phone_number='09393214333',
        email='officialfardinzand@gmail.com',
        first_name='Fardin',
        last_name='Moghaddam pour',
        age=22,
        profile_image='profile_images/User_Default_Profile_Pic.png'
    )

    CustomUser.objects.create(
        username='Mahmoud_MP',
        password='12345678',
        phone_number='09166060286',
        first_name='Mahmoud',
        last_name='Moghaddam pour',
        age=65,
        profile_image='profile_images/User_Default_Profile_Pic.png'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_address_unique_together'),
    ]

    operations = [
        migrations.RunPython(populate_users),
    ]
