# Generated by Django 5.0.4 on 2024-05-01 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='product_media/default.png', upload_to='product_media/'),
        ),
    ]
